# Generated by Django 2.1.2 on 2018-11-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=20, verbose_name='Name of The Song:')),
                ('artist', models.CharField(max_length=20, verbose_name='Artist:')),
                ('comments', models.TextField(verbose_name='Your View on the Song:')),
            ],
        ),
    ]
